stages:
  spaceship-titanic-load:
    cmd: cd kaggle_competitions/spaceship_titanic/data && poetry run kaggle competitions download -c spaceship-titanic && unzip spaceship-titanic.zip && rm spaceship-titanic.zip
    outs:
      - kaggle_competitions/spaceship_titanic/data/train.csv
      - kaggle_competitions/spaceship_titanic/data/test.csv
      - kaggle_competitions/spaceship_titanic/data/sample_submission.csv
  spaceship-titanic-run:
    cmd: poetry run spaceship_titanic
    deps:
      - kaggle_competitions/spaceship_titanic/run.py
      - kaggle_competitions/metrics.py
      - kaggle_competitions/spaceship_titanic/data/train.csv
      - kaggle_competitions/spaceship_titanic/data/test.csv
      - kaggle_competitions/spaceship_titanic/data/sample_submission.csv
    outs:
      - kaggle_competitions/spaceship_titanic/data/submission.csv
    metrics:
      - kaggle_competitions/spaceship_titanic/metrics.json
  spaceship-titanic-submit:
    frozen: false
    cmd: poetry run kaggle competitions submit -c spaceship-titanic -f ./kaggle_competitions/spaceship_titanic/data/submission.csv -m "Automatic submit"
    deps:
      - kaggle_competitions/spaceship_titanic/data/submission.csv
