stages:
  spaceship-titanic-load:
    cmd: mkdir -p data && cd data && poetry run kaggle competitions download -c spaceship-titanic && unzip spaceship-titanic.zip && rm spaceship-titanic.zip
    outs:
      - data/train.csv
      - data/test.csv
      - data/sample_submission.csv
  spaceship-titanic-run:
    cmd: poetry run spaceship_titanic
    deps:
      - run.py
      - ../metrics.py
      - data/train.csv
      - data/test.csv
      - data/sample_submission.csv
    outs:
      - data/submission.csv
    metrics:
      - metrics.json
  spaceship-titanic-submit:
    frozen: true
    cmd: poetry run kaggle competitions submit -c spaceship-titanic -f ./data/submission.csv -m "Automatic submit"
    deps:
      - data/submission.csv
